version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: event_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: event_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/eventsdb
      - JWT_SECRET=supersecret
    depends_on:
      - mongodb

  auth-service:
    build: ./auth-service
    container_name: auth_service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - JWT_SECRET=auth-secret-key

  event-service:
    build: ./event-service
    container_name: event_service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://mongodb:27017/eventsdb

  booking-service:
    build: ./booking-service
    container_name: booking_service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - EVENT_SERVICE_URL=http://event-service:3002
      - MONGO_URI=mongodb://mongodb:27017/eventsdb
    depends_on:
      - event-service

  frontend:
    build: ./frontend
    container_name: event_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
